### ISSUE TITLE
Negative setpoint not taken care of

### ISSUE THREAD

**Issue by stefboerrigterWavin** [stefboerrigter/wavinsentio-ha#1]
Negative setpoint is shown wrong:
![image](https://github.com/stefboerrigter/wavinsentio-ha/assets/86054364/0ca3d474-9ba1-4db2-be67-e0542aa25bcc)
have setup -5.0 for VINO and -5.46 for PIVO, in FP100 format it is around -500, result is 65036 in uint16_t datatype

**Comment by stefboerrigterWavin** [comment]
Fixed in PyModbus library

**Comment by stefboerrigter** [comment]
please check with updated version @JanSpulak

**Comment by stefboerrigter** [comment]
![image](https://github.com/stefboerrigter/wavinsentio-ha/assets/4964819/ba303e08-0499-4f94-9875-48b2823f56f5)
Not fixed..

**Comment by stefboerrigterWavin** [comment]
Fixed: 
![image](https://github.com/stefboerrigter/wavinsentio-ha/assets/86054364/f6f62663-0ee3-43e6-b620-2e45a61d991b)
